Clean build and release jobs
* Improve REAMDE instructions
* No more install.sh
* Better CI workflow
* Clean up macros

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,261 +11,201 @@ on:
       - dev
 
 jobs:
-  # Special build that builds with profiling and coverage
-  build-profile:
-    runs-on: ubuntu-latest
+
+  binary:
     strategy:
       matrix:
-        compiler: [gcc, clang]
-    steps:
-    - name: Checkout Code
-      uses: actions/checkout@v4
+        include:
 
-    # Plus gcovr for code coverage
-    - name: Install Build Dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y \
-          python3-pip \
-          python3-setuptools \
-          ninja-build \
-          build-essential \
-          xxd \
-          wget \
-          pkg-config \
-          libncurses-dev \
-          libargtable2-dev
-        pip3 install meson gcovr
+            # Release builds
 
-    - name: Build for Linux x86_64
-      env:
-        CC: ${{ matrix.compiler }}
-      run: |
-        sh install.sh --coverage
-
-    - name: Run Tests
-      run: |
-        meson test -v -C build
-
-    - name: Generate Code Coverage Reports
-      run: |
-        ninja coverage-xml -C build
-
-    - name: Upload Coverage
-      uses: actions/upload-artifact@v3
-      with:
-        name: coverage
-        path: build/meson-logs/coverage.xml
-
-  build-linux:
-    runs-on: ubuntu-20.04 # Use an older Ubuntu version to ensure compatibility with older C libraries
-    strategy:
-      matrix:
-        compiler: [gcc, clang]
-    steps:
-    - name: Checkout Code
-      uses: actions/checkout@v4
-
-    # Plus gcovr for code coverage
-    - name: Install Build Dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y \
-          python3-pip \
-          python3-setuptools \
-          ninja-build \
-          build-essential \
-          xxd \
-          wget \
-          pkg-config \
-          libncurses-dev \
-          libargtable2-dev
-        pip3 install meson gcovr
-
-    - name: Build for Linux x86_64
-      env:
-        CC: ${{ matrix.compiler }}
-      run: |
-        sh install.sh
-
-    - name: Run Tests
-      run: |
-        meson test -v -C build
-
-    - name: Upload x86_64 Build Artifacts
-      # Only use result of one compiler
-      if: matrix.compiler == 'gcc'
-      uses: actions/upload-artifact@v3
-      with:
-        name: astroterm-linux-x86_64
-        path: build/astroterm
-
-  run-linux:
-    runs-on: ubuntu-latest
-    needs: build-linux
-    steps:
-      - name: Download Build Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: astroterm-linux-x86_64
-          path: astroterm-linux-x86_64
-
-      - name: Make Executable
-        run: |
-          chmod +x astroterm-linux-x86_64/astroterm
-
-      - name: Run Executable
-        run: |
-          ./astroterm-linux-x86_64/astroterm --version
-
-  build-darwin:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [macos-latest, macos-13]
-        arch: [aarch64, x86_64]
-        exclude:
-          - os: macos-latest
+            # astroterm-linux-x86_64
+            # Use an older Ubuntu version to ensure compatibility with older C libraries
+          - os: ubuntu-20.04
+            suffix: linux
+            compiler: gcc
             arch: x86_64
-          - os: macos-13
-            arch : aarch64
 
-    steps:
-    - name: Checkout Code
-      uses: actions/checkout@v4
-
-    - name: Install Build Dependencies
-      run: |
-        brew update
-        brew install \
-          meson \
-          ninja \
-          ncurses \
-          argtable
-
-    - name: Build for Darwin ${{ matrix.arch }}
-      env:
-        CC: clang
-      run: |
-        sh install.sh
-
-    - name: Run Tests
-      run: |
-        meson test -v -C build
-
-    - name: Upload Darwin ${{ matrix.arch }} Build Artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: astroterm-darwin-${{ matrix.arch }}
-        path: build/astroterm
-
-  run-darwin:
-    runs-on: ${{ matrix.os }}
-    needs: build-darwin  # Ensure this depends on the build job
-    strategy:
-      matrix:
-        os: [macos-latest, macos-13]
-        arch: [aarch64, x86_64]
-        exclude:
+            # astroterm-darwin-aarch64
           - os: macos-latest
-            arch: x86_64
-          - os: macos-13
+            suffix: darwin
+            compiler: clang
             arch: aarch64
 
-    steps:
-      - name: Download Darwin ${{ matrix.arch }} Build Artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: astroterm-darwin-${{ matrix.arch }}
+            # astroterm-darwin-x86_64
+          - os: macos-13
+            suffix: darwin
+            compiler: clang
+            arch: x86_64
 
-      - name: Make Executable
-        run: |
-          chmod +x astroterm
+            # astroterm-win-x86_64
+          - os: windows-latest
+            suffix: win
+            compiler: cl #mscv
+            arch: x86_64
 
-      - name: Run Executable
-        run: |
-          ./astroterm --version
+            # Coverage build
 
-  build-win:
+          - os: ubuntu-20.04
+            suffix: linux
+            arch: x86_64
+            compiler: gcc
+            coverage: true
+
+      fail-fast: false
     runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [windows-latest, windows-2019]
 
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v4
+      - name: Checkout Code
+        uses: actions/checkout@v4
 
-    - name: Setup Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
+      # ------------------------------------------------------------------------
+      # Linux Dependencies
+      # ------------------------------------------------------------------------
+      # gcovr is for coverage build
 
-    - name: Install Python Dependencies
-      run: pip install meson ninja
-
-    - name: Prepare MSVC
-      uses: bus1/cabuild/action/msdevshell@v1
-      with:
-        architecture: x64
-
-    # I tried the 3.9 release, something broke, so sticking with cloning main for now
-    - name: Clone and Build PDCurses
-      run: |
-        mkdir .\install\lib
-        mkdir .\install\include
-        cd .\install
-        git clone https://github.com/wmcbrine/PDCurses/
-        cd PDCurses\wincon
-        nmake -f Makefile.vc WIDE=Y UTF8=Y
-        copy pdcurses.lib ..\..\lib
-        copy ..\curses.h ..\..\include
-        copy ..\panel.h ..\..\include
-
-    - name: Download and Build Argtable2
-      run: |
-        cd .\install
-        curl -L -o argtable2-13.tar.gz http://prdownloads.sourceforge.net/argtable/argtable2-13.tar.gz
-        tar -xzf argtable2-13.tar.gz
-        cd .\argtable2-13\src
-        nmake -f Makefile.nmake
-        copy argtable2.lib ..\..\lib
-        copy argtable2.h ..\..\include
-
-    - name: Download BSC5
-      run: curl -L -o data/bsc5 http://tdc-www.harvard.edu/catalogs/BSC5 || echo "bsc5 already exists or curl failed"
-
-    - name: Build for Windows x86_64
-      run: |
-        meson setup build -Drelease_build=true
-        meson compile -C build
-
-    - name: Run Tests
-      run: |
-        meson test -v -C build
-
-    - name: Upload Windows x86_64 Build Artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: astroterm-win-x86_64
-        path: build/astroterm.exe
-
-  run-win:
-    runs-on: windows-latest
-    needs: build-win
-    steps:
-      - name: Download Windows Build Artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: astroterm-win-x86_64
-
-      - name: Run Executable
+      - name: Install Linux Dependencies
+        if: matrix.suffix == 'linux'
         run: |
-          .\astroterm.exe --version
+          sudo apt-get update
+          sudo apt-get install -y \
+            python3-pip \
+            python3-setuptools \
+            ninja-build \
+            build-essential \
+            xxd \
+            wget \
+            pkg-config \
+            libncurses-dev \
+            libargtable2-dev
+          pip3 install meson gcovr
+
+      # ------------------------------------------------------------------------
+      # macOS Dependencies
+      # ------------------------------------------------------------------------
+
+      - name: Install macOS Dependencies
+        if: matrix.suffix == 'darwin'
+        run: |
+          brew update
+          brew install \
+            meson \
+            ninja \
+            ncurses \
+            argtable
+
+      # ------------------------------------------------------------------------
+      # Windows Dependencies
+      # ------------------------------------------------------------------------
+
+      - name: Setup Python
+        if: matrix.suffix == 'win'
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
+
+      - name: Install Python Dependencies
+        if: matrix.suffix == 'win'
+        run: pip install meson ninja
+
+      - name: Prepare MSVC
+        if: matrix.suffix == 'win'
+        uses: bus1/cabuild/action/msdevshell@v1
+        with:
+          architecture: x64
+
+      - name: Clone and Build PDCurses
+        if: matrix.suffix == 'win'
+        run: |
+          mkdir .\install\lib
+          mkdir .\install\include
+          cd .\install
+          git clone https://github.com/wmcbrine/PDCurses/
+          cd PDCurses\wincon
+          nmake -f Makefile.vc WIDE=Y UTF8=Y
+          copy pdcurses.lib ..\..\lib
+          copy ..\curses.h ..\..\include
+          copy ..\panel.h ..\..\include
+
+      - name: Download and Build Argtable2
+        if: matrix.suffix == 'win'
+        run: |
+          cd .\install
+          curl -L -o argtable2-13.tar.gz http://prdownloads.sourceforge.net/argtable/argtable2-13.tar.gz
+          tar -xzf argtable2-13.tar.gz
+          cd .\argtable2-13\src
+          nmake -f Makefile.nmake
+          copy argtable2.lib ..\..\lib
+          copy argtable2.h ..\..\include
+
+      # ------------------------------------------------------------------------
+      # Build and test
+      # ------------------------------------------------------------------------
+
+      - name: Download BSC5
+        run: curl -L -o data/bsc5 http://tdc-www.harvard.edu/catalogs/BSC5 || echo "bsc5 already exists or curl failed"
+
+      - name: Build
+        env:
+          CC: ${{ matrix.compiler }}
+          BuildFlag:  ${{ matrix.coverage && '-Db_coverage=true' || '-Drelease_build=true'}}
+        run: |
+          meson setup build $BuildFlag
+          meson compile -C build
+
+      - name: Test
+        run: |
+          meson test -v -C build
+
+      # ------------------------------------------------------------------------
+      # Compute Coverage
+      # ------------------------------------------------------------------------
+
+      - name: Generate Code Coverage Reports
+        if: matrix.coverage
+        run: |
+          ninja coverage-xml -C build
+
+      - name: Upload Coverage
+        if: matrix.coverage
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage
+          path: build/meson-logs/coverage.xml
+
+      # ------------------------------------------------------------------------
+      # Upload Binary
+      # ------------------------------------------------------------------------
+
+      - name: Upload Binary
+        if: matrix.coverage == false
+        env:
+            ArtifactName: astroterm-${{ matrix.suffix }}-${{ matrix.arch }}
+        uses: actions/upload-artifact@v4
+        with:
+            name: ${{ matrix.suffix == 'win' && format('{0}.exe', env.ArtifactName) || format('{0}', env.ArtifactName) }}
+            path: ${{ matrix.suffix == 'win' && 'build/astroterm.exe' || 'build/astroterm' }}
+
+      # ------------------------------------------------------------------------
+      # Generate Hash
+      # ------------------------------------------------------------------------
+
+      - name: Generate Hash
+        run:
+            ${{ matrix.suffix == 'win' &&  'certutil -hashfile build/astroterm.exe SHA256' || 'shasum -a 256 build/astroterm' }} > build/hash.sha256
+
+      - name: Upload Hash
+        if: matrix.coverage != true
+        uses: actions/upload-artifact@v4
+        env:
+            ArtifactName: astroterm-${{ matrix.suffix }}-${{ matrix.arch }}
+        with:
+            name: ${{ matrix.suffix == 'win' && format('{0}.exe.sha256', env.ArtifactName) || format('{0}.sha256', env.ArtifactName) }}
+            path: build/hash.sha256
 
   code-quality:
     runs-on: ubuntu-latest
-    needs: build-profile
+    needs: binary
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v4
@@ -293,7 +233,7 @@ jobs:
     needs: code-quality
     steps:
     - name: Download Coverage Reports
-      uses: actions/download-artifact@v3
+      uses: actions/download-artifact@v4
       with:
         name: coverage
         path: coverage
@@ -307,49 +247,22 @@ jobs:
 
   publish-release:
     runs-on: ubuntu-latest
-    needs: [run-linux, run-darwin, run-win, code-quality, upload-coverage]
+    needs: [binary, code-quality, upload-coverage]
     if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
     steps:
 
-    - name: Download Build astroterm-linux-x86_64
-      uses: actions/download-artifact@v3
+    - name: Download Release Binaries
+      uses: actions/download-artifact@v4
       with:
-        name: astroterm-linux-x86_64
-        path: astroterm-linux-x86_64
-
-    - name: Download Build astroterm-darwin-x86_64
-      uses: actions/download-artifact@v3
-      with:
-        name: astroterm-darwin-x86_64
-        path: astroterm-darwin-x86_64
-
-    - name: Download Build astroterm-darwin-aarch64
-      uses: actions/download-artifact@v3
-      with:
-        name: astroterm-darwin-aarch64
-        path: astroterm-darwin-aarch64
-
-    - name: Download Build astroterm-win-x84_64
-      uses: actions/download-artifact@v3
-      with:
-        name: astroterm-win-x84_64
-        path: astroterm-win-x84_64
-
-    - name: Generate Changelog
-      id: changelog
-      uses: Requarks/changelog-action@v1
-      with:
-        token: ${{ github.token }}
-        tag: ${{ github.ref_name }}
-        writeToFile: false
+        pattern: astroterm-*
+        path: ./bin/release
+        merge-multiple: true
 
     - name: Update GitHub Release
-      uses: ncipollo/release-action@v1.12.0
+      uses: ncipollo/release-action@58ae73b360456532aafd58ee170c045abbeaee37 # v1.10.0
       with:
-        allowUpdates: true
+        artifacts: ./bin/release
+        generateReleaseNotes: true
         draft: true
-        makeLatest: true
-        name: ${{ github.ref_name }}
-        body: ${{ steps.changelog.outputs.changes }}
         token: ${{ secrets.GITHUB_TOKEN }}
-        artifacts: 'astroterm-linux-x86_64,astroterm-darwin-aarch64,astroterm-darwin-x86_64,astroterm-win-x86_64'
+        name: ${{ github.ref_name }}
